matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - g++
            - qtchooser
            - qt5-default
            - libqt5svg5-dev
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5charts5
            - libqt5charts5-dev
            - libboost-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-thread-dev
            - pkg-config
before_install:
      - eval "${MATRIX_EVAL}"
